name = "ai-relay"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[[kv_namespaces]]
binding = "KV"

[[d1_databases]]
binding = "DB"
database_name = "ai-relay"
migrations_dir = "migrations"

