'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';
import { formatLargeNumber, formatWithThousandSeparator } from '../lib/format';

type Metric = 'requests' | 'totalTokens' | 'promptTokens' | 'completionTokens';
type Preset = '7d' | '30d' | 'custom';

interface TrendPoint {
  date: string;
  requests: number;
  totalTokens: number;
  promptTokens: number;
  completionTokens: number;
}

interface UsageReportResponse {
  range: { from: string; to: string };
  reports: Array<{
    date: string;
    byProvider?: Record<string, { requests?: number; tokens?: number; promptTokens?: number; completionTokens?: number }>;
  }>;
  trend: TrendPoint[];
}

interface Props {
  apiKey: string;
  lang: 'zh' | 'en';
}

const metricColors: Record<Metric, string> = {
  requests: '#60a5fa',
  totalTokens: '#34d399',
  promptTokens: '#fbbf24',
  completionTokens: '#a78bfa',
};

function formatDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}


function rangeForPreset(preset: Preset, customRange: { from: string; to: string }): { from: string; to: string } {
  if (preset === 'custom' && customRange.from && customRange.to) return customRange;
  const to = new Date();
  const from = new Date(to);
  from.setUTCDate(to.getUTCDate() - (preset === '30d' ? 29 : 6));
  return { from: formatDate(from), to: formatDate(to) };
}

function defaultCustomRange(): { from: string; to: string } {
  return rangeForPreset('7d', { from: '', to: '' });
}

export default function UsageReportTab({ apiKey, lang }: Props) {
  const isEn = lang === 'en';
  const [preset, setPreset] = useState<Preset>('7d');
  const [customRange, setCustomRange] = useState(defaultCustomRange);
  const [metric, setMetric] = useState<Metric>('totalTokens');
  const [data, setData] = useState<UsageReportResponse | null>(null);
  const [selectedProviders, setSelectedProviders] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const labels = {
    title: isEn ? '📈 Usage Report' : '📈 用量报告',
    desc: isEn ? 'Daily reports generated by Cron with zero-filled gaps.' : '由 Cron 生成的日报趋势，缺口日期自动补 0。',
    refresh: isEn ? 'Refresh' : '刷新',
    loading: isEn ? 'Loading...' : '加载中...',
    noData: isEn ? 'No report data in this range.' : '当前范围暂无日报数据。',
    requests: isEn ? 'Requests' : '请求数',
    totalTokens: isEn ? 'Total Tokens' : '总 Token',
    promptTokens: isEn ? 'Prompt Tokens' : '输入 Token',
    completionTokens: isEn ? 'Completion Tokens' : '输出 Token',
    providers: isEn ? 'Providers' : '供应商筛选',
    allProviders: isEn ? 'All providers' : '全部供应商',
    customRange: isEn ? 'Custom' : '自定义',
    from: isEn ? 'From' : '开始日期',
    to: isEn ? 'To' : '结束日期',
  };

  const fetchReport = useCallback(async () => {
    const range = rangeForPreset(preset, customRange);
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/admin/usage-report?from=${range.from}&to=${range.to}`, {
        headers: { Authorization: `Bearer ${apiKey}` },
        cache: 'no-store',
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error?.message || 'Failed to load usage report');
      setData(json);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setLoading(false);
    }
  }, [apiKey, preset, customRange]);

  useEffect(() => {
    fetchReport();
  }, [fetchReport]);

  const providerIds = useMemo(() => {
    const ids = new Set<string>();
    data?.reports.forEach((report) => Object.keys(report.byProvider || {}).forEach((id) => ids.add(id)));
    return Array.from(ids).sort();
  }, [data]);

  const chartData = useMemo(() => {
    if (!data || selectedProviders.length === 0) return data?.trend || [];
    const byDate = new Map(data.reports.map((report) => [report.date, report]));
    return data.trend.map((point) => {
      const report = byDate.get(point.date);
      const aggregate = selectedProviders.reduce((sum, provider) => {
        const item = report?.byProvider?.[provider];
        return {
          requests: sum.requests + Number(item?.requests || 0),
          totalTokens: sum.totalTokens + Number(item?.tokens || 0),
          promptTokens: sum.promptTokens + Number(item?.promptTokens || 0),
          completionTokens: sum.completionTokens + Number(item?.completionTokens || 0),
        };
      }, { requests: 0, totalTokens: 0, promptTokens: 0, completionTokens: 0 });
      return { ...point, ...aggregate };
    });
  }, [data, selectedProviders]);

  const toggleProvider = (provider: string) => {
    setSelectedProviders((current) => current.includes(provider)
      ? current.filter((item) => item !== provider)
      : [...current, provider]);
  };

  const selectPreset = (nextPreset: Preset) => {
    setPreset(nextPreset);
    if (nextPreset !== 'custom') setCustomRange(rangeForPreset(nextPreset, customRange));
  };

  return (
    <div className="glass-panel" style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: '1rem', alignItems: 'center', flexWrap: 'wrap' }}>
        <div>
          <h2 style={{ margin: 0, color: '#fff' }}>{labels.title}</h2>
          <p style={{ margin: '0.35rem 0 0', color: '#9ca3af' }}>{labels.desc}</p>
        </div>
        <button className="tab-btn active" onClick={fetchReport} disabled={loading}>{loading ? labels.loading : labels.refresh}</button>
      </div>

      <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
        {(['7d', '30d'] as const).map((item) => (
          <button key={item} className={`tab-btn ${preset === item ? 'active' : ''}`} onClick={() => selectPreset(item)}>{item}</button>
        ))}
        <button className={`tab-btn ${preset === 'custom' ? 'active' : ''}`} onClick={() => selectPreset('custom')}>{labels.customRange}</button>
        {(['requests', 'totalTokens', 'promptTokens', 'completionTokens'] as const).map((item) => (
          <button key={item} className={`tab-btn ${metric === item ? 'active' : ''}`} onClick={() => setMetric(item)}>{labels[item]}</button>
        ))}
      </div>

      {preset === 'custom' && (
        <div className="stat-card" style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap', alignItems: 'center' }}>
          <label style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', color: '#9ca3af', fontSize: '0.85rem' }}>
            {labels.from}
            <input
              type="date"
              value={customRange.from}
              max={customRange.to}
              onChange={(event) => setCustomRange((current) => ({ ...current, from: event.target.value }))}
              style={{ colorScheme: 'dark' }}
            />
          </label>
          <label style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', color: '#9ca3af', fontSize: '0.85rem' }}>
            {labels.to}
            <input
              type="date"
              value={customRange.to}
              min={customRange.from}
              max={formatDate(new Date())}
              onChange={(event) => setCustomRange((current) => ({ ...current, to: event.target.value }))}
              style={{ colorScheme: 'dark' }}
            />
          </label>
        </div>
      )}

      {providerIds.length > 0 && (
        <div className="stat-card" style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', alignItems: 'center' }}>
          <span style={{ color: '#9ca3af', fontSize: '0.85rem' }}>{labels.providers}</span>
          <button className={`tab-btn ${selectedProviders.length === 0 ? 'active' : ''}`} onClick={() => setSelectedProviders([])}>{labels.allProviders}</button>
          {providerIds.map((provider) => (
            <button key={provider} className={`tab-btn ${selectedProviders.includes(provider) ? 'active' : ''}`} onClick={() => toggleProvider(provider)}>{provider}</button>
          ))}
        </div>
      )}

      {error && <div className="stat-card" style={{ color: '#f87171' }}>{error}</div>}
      {!error && chartData.length === 0 && <div className="stat-card" style={{ color: '#9ca3af' }}>{loading ? labels.loading : labels.noData}</div>}
      {!error && chartData.length > 0 && (
        <div className="stat-card" style={{ height: 320 }}>
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={chartData} margin={{ top: 12, right: 20, left: 15, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.08)" />
              <XAxis dataKey="date" stroke="#9ca3af" tick={{ fontSize: 12 }} />
              <YAxis stroke="#9ca3af" tick={{ fontSize: 12 }} tickFormatter={formatLargeNumber} width={60} />
              <Tooltip
                contentStyle={{ background: '#111827', border: '1px solid rgba(255,255,255,0.12)', borderRadius: 8 }}
                formatter={(value) =>
                  typeof value === 'number' || typeof value === 'string'
                    ? formatWithThousandSeparator(value, lang === 'zh' ? 'zh-CN' : 'en-US')
                    : String(value)
                }
              />
              <Line type="monotone" dataKey={metric} name={labels[metric]} stroke={metricColors[metric]} strokeWidth={2.5} dot={false} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      )}
    </div>
  );
}
